# Generated by Django 6.0.4 on 2026-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Image', models.ImageField(upload_to='image')),
                ('Pass', models.CharField(max_length=20)),
                ('CPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Add_Employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
