# Generated by Django 6.0.4 on 2026-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_delete_add_employee_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.BigIntegerField()),
                ('Image', models.ImageField(upload_to='image')),
                ('Code', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=40)),
                ('dep_desc', models.CharField(max_length=40)),
                ('dep_head', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_desc', models.CharField(max_length=40)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='image')),
                ('item_color', models.CharField(max_length=20)),
                ('item_category', models.CharField(max_length=40)),
                ('item_quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Emp_id', models.CharField(max_length=40)),
                ('Dept', models.CharField(max_length=40)),
                ('Query', models.CharField(max_length=80)),
                ('Status', models.CharField(default='pending')),
                ('Reply', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
