# Generated by Django 5.2.13 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_order_alter_add_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_employee',
            name='Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
