# Generated by Django 5.2.13 on 2026-04-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_add_employee_contact_alter_employee_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
