# Generated by Django 5.2.13 on 2026-04-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_add_employee_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
