# Generated by Django 5.2.13 on 2026-04-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CPass',
        ),
    ]
