# Generated by Django 5.2.13 on 2026-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_user_cpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CPass',
            field=models.CharField(default='', max_length=20),
        ),
    ]
